version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

  mysql:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
      - "23306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  ms-auth:
    image: ms-auth
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - default

  ms-products:
    image: ms-products
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/products
      - RABBITMQ_HOST=rabbitmq
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - default

  ms-orders:
    image: ms-orders
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/orders
      - RABBITMQ_HOST=rabbitmq
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - default

  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
    networks:
      - default
networks:
  default: