spring:
  application:
    name: ms-orders
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/orders}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:admin}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
server:
  port: 8083