spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
server:
  port: 8082
