spring:
  application:
    name: ms-products
  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8082
