spring:
  application:
    name: ms-auth
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/auth}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:admin}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081
app:
  jwt-secret: "ed20c13a47e6becb1eaf82af2b75f7b1edf0facecca2421090eed861cacec57b"
  jwt-expiration-in-ms: "86400000"