spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
server:
  port: 8081
app:
  jwt-secret: "secret"
  jwt-expiration-in-ms: "86400000"