spring:
  application:
    name: api-gateway

server:
  port: 8080

authentication-service-url: http://ms-auth:8081
products-service-url: http://ms-products:8082
orders-service-url: http://ms-orders:8083
